### ISSUE TITLE
urx.urrobot.RobotException: Goal not reached but no program has been running for 5 seconds. 

### ISSUE THREAD

**Issue by majunqiao** [SintefManufacturing/python-urx#104]
I used urx version 3.5 to control ur5e, but this problem still occurs. Why
---------------------------------
Traceback (most recent call last):
  File "F:/python-urx-SW3.5/examples/simple.py", line 22, in <module>
    rob.movel(pose, acc=a, vel=v)
  File "F:\python-urx-SW3.5\urx\urrobot.py", line 284, in movel
    return self.movex("movel", tpose, acc=acc, vel=vel, wait=wait, relative=relative, threshold=threshold)
  File "F:\python-urx-SW3.5\urx\robot.py", line 180, in movex
    return self.set_pose(t, acc, vel, wait=wait, command=command, threshold=threshold)
  File "F:\python-urx-SW3.5\urx\robot.py", line 105, in set_pose
    pose = URRobot.movex(self, command, t.pose_vector, acc=acc, vel=vel, wait=wait, threshold=threshold)
  File "F:\python-urx-SW3.5\urx\urrobot.py", line 316, in movex
    self._wait_for_move(tpose[:6], threshold=threshold)
  File "F:\python-urx-SW3.5\urx\urrobot.py", line 226, in _wait_for_move
    raise RobotException("Goal not reached but no program has been running for {} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format(timeout, dist, threshold, target, URRobot.getl(self)))
urx.urrobot.RobotException: Goal not reached but no program has been running for 5 seconds. dist is 0.05002519864850817, threshold is 0.039997401975197716, target is [-0.14482952 -0.30244127  0.50539086  0.26118166  3.11185305 -0.02753296], current pose is [-0.14483181529289282, -0.302446863891004, 0.45536571858131486, 0.2611981383037345, 3.111843703775645, -0.027413989906807854]

**Comment by yassirnajmaoui** [comment]
I get the same error on a UR5
