### ISSUE TITLE
pip install urx (install error)

### ISSUE THREAD

**Issue by cheabdullahjz** [SintefManufacturing/python-urx#116]
(env) (base) C:\Users\AAA>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import urx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AAA\env\lib\site-packages\urx\__init__.py", line 4, in <module>
    from urx.urrobot import RobotException, URRobot  # noqa
  File "C:\Users\AAA\env\lib\site-packages\urx\urrobot.py", line 9, in <module>
    from urx import urrtmon
  File "C:\Users\AAA\env\lib\site-packages\urx\urrtmon.py", line 16, in <module>
    import math3d as m3d
  File "C:\Users\AAA\env\lib\site-packages\math3d\__init__.py", line 21, in <module>
    from .transform import Transform, PoseVector
  File "C:\Users\AAA\env\lib\site-packages\math3d\transform.py", line 156, in <module>
    class Transform(object):
  File "C:\Users\AAA\env\lib\site-packages\math3d\transform.py", line 528, in Transform
    ApTs: typing.Union[np.ndarray, tuple[PositionVector]],
TypeError: 'type' object is not subscriptable
>>>

**Comment by cheabdullahjz** [comment]
RuntimeError: Python version >= 3.9 required.

**Comment by cheabdullahjz** [comment]
Steps for solving this issue
a) https://www.anaconda.com/download (Download new anaconda e.g.:3.11)
b) python -m virtualenv .venv -p python3.9
c) .\env\Scripts\activate
d) python (and test import urx)

(.venv) D:\URX_VENV\python-urx-master>python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import urx
